repository:
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 0
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - lint-pr / Validate PR title
      enforce_admins: true
      required_linear_history: true
