name: Release Please

on:
  workflow_call:

permissions:
  contents: write

jobs:
  parse-semver:
    runs-on: ubuntu-latest
    outputs:
      major: ${{ steps.version.outputs.major }}
      minor: ${{ steps.version.outputs.minor }}
      patch: ${{ steps.version.outputs.patch }}
    steps:
      - name: parse semver
        id: version
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.event.release.name }}
          version_extractor_regex: "^v(.*)$"
  release-please:
    runs-on: ubuntu-latest
    needs: parse-semver
    strategy:
      matrix:
        version:
          [
            "${{ needs.parse-semver.outputs.major }}",
            "${{ needs.parse-semver.outputs.major }}.${{ needs.parse-semver.outputs.minor }}",
            "v${{ needs.parse-semver.outputs.major }}",
            "v${{ needs.parse-semver.outputs.major }}.${{ needs.parse-semver.outputs.minor }}",
          ]
    steps:
      - uses: actions/checkout@v4
      - name: tag version ${{ matrix.version }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d ${{ matrix.version }} || true
          git push origin :${{ matrix.version }} || true
          git tag -a ${{ matrix.version }} -m "Release ${{ matrix.version }}"
          git push origin ${{ matrix.version }}
