on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    uses: ./.github/workflows/release-please.yml
    secrets: inherit
    with:
      release-type: "simple"
