name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: ./.github/workflows/release-please.yml
    secrets: inherit
    with:
      release-type: "simple"
