name: Publish

on:
  workflow_call:
    inputs:
      toolchain:
        description: "Rust toolchain specification -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification"
        required: false
        default: stable
        type: string
    secrets:
      CARGO_REGISTRY_TOKEN:
        description: "Token for authenticating with the Cargo registry"
        required: true

permissions:
  contents: read

jobs:
  publish-to-cargo:
    name: Publish to Cargo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
