name: Publish Documentation

on:
  workflow_call:
    inputs:
      toolchain:
        description: "Rust toolchain specification -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification"
        required: false
        default: stable
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}
      - name: Build documentation
        run: cargo doc --no-deps
      - name: Get parent folder name
        id: folder
        run: echo "folder=$(basename $(dirname ./target/doc/*/index.html))" >> $GITHUB_OUTPUT
      - name: Setup index page
        run: |
          echo "<meta http-equiv=\"refresh\" content=\"0; url=${{ steps.folder.outputs.folder }}\">" > target/doc/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "target/doc"
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
