name: Test
on:
  workflow_call:

jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Test
        run: bunx vitest --coverage.enabled true

      - name: Report Coverage
        if: always() && github.event_name == 'pull_request'
        uses: davelosert/vitest-coverage-report-action@v2
